unstable_features = true

imports_granularity = 'Module'
group_imports = "StdExternalCrate"
struct_lit_width = 30
single_line_let_else_max_width = 60
chain_width = 80
fn_call_width = 65
fn_single_line = true
where_single_line = true
use_field_init_shorthand = true
reorder_impl_items = true
overflow_delimited_expr = true
brace_style = 'PreferSameLine'
